org: marco49
app: everymundo-fares-challenge
service: serverless-currency-formats
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  environment:
    DB_HOST: ${ssm:/DB_HOST_EVERYMUNDO~true}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
